# Generated by Django 5.2.8 on 2025-11-12 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Courte biographie optionnelle', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=2, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='destinataire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text="Groupes d'appartenance", related_name='custom_user_groups', to='auth.group', verbose_name='groupes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissions spécifiques de cet utilisateur', related_name='custom_user_permissions', to='auth.permission', verbose_name='permissions utilisateur'),
        ),
    ]
