# Generated by Django 5.2.8 on 2025-11-12 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notifications', '0002_alter_user_options_user_bio_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_perso_db',
            field=models.EmailField(default='perso@domaine.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_db',
            field=models.CharField(default='+00000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='priority_db',
            field=models.CharField(default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='time_window_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='time_window_start',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_permissions', to='auth.permission'),
        ),
    ]
