# Generated by Django 5.2.8 on 2025-11-12 05:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_user_email_perso_db_user_phone_db_user_priority_db_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_window_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='time_window_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
